[package]
name = "pro1"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.30.0"
secp256k1 = { version = "0.28", features = ["rand", "serde"] }
bitcoin_hashes = "0.14"
sha2 = "0.10"
ripemd = "0.1"
base58 = "0.2"
rand= "0.8"
hex = "0.4"
